version = 2
final_space = true
console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'

[[blocks]]
    type = 'prompt'
    alignment = 'left'

    [[blocks.segments]]
        type = 'path'
        style = 'plain'
        background = 'transparent'
        foreground = 'p:primary'
        template = '{{ .Path }} '

        [blocks.segments.properties]
            style = 'full'

    [[blocks.segments]]
        type = 'git'
        style = 'plain'
        foreground = 'p:gray'
        background = 'transparent'
        template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:secondary>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

        [blocks.segments.properties]
            branch_icon = ''
            commit_icon = '@'
            fetch_status = true

[[blocks]]
    type = 'rprompt'
    alignment = 'right'
    overflow = 'hidden'

    [[blocks.segments]]
        type = 'executiontime'
        style = 'plain'
        foreground = 'p:primary'
        background = 'transparent'
        template = '{{ .FormattedMs }}'

        [blocks.segments.properties]
            threshold = 5000


[[blocks]]
    type = 'prompt'
    alignment = 'left'

    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        background = 'transparent'
        foreground_templates = [
            "{{ if gt .Code 0 }}p:error{{ end }}",
            "{{ if eq .Code 0 }}p:accent{{ end }}",
        ]
        template = "❯"

[transient_prompt]
    background = 'transparent'
    foreground_templates = [
        "{{ if gt .Code 0 }}p:error{{ end }}",
        "{{ if eq .Code 0 }}p:accent{{ end }}",
    ]
    template = "❯ "

[secondary_prompt]
    background = 'transparent'
    foreground = 'p:accent'
    template = "❯❯ "

[palette]
gray = '#6c6c6c'
primary = '#deae57'
secondary = 'blue'
error = 'red'
accent = '#ffffff'
